### ISSUE TITLE
New bug in tower addition

### ISSUE THREAD

**Issue by mhaghighat20** [altostratous/borooj#1]
In configuration.xml we have 3 commands for adding 3 towers to invalid positions (those three cells belong to paths) but in first three printed lines in cmd we see that it says:
Game started successfully!
Tower added successfully!
Tower added successfully!
Tower added successfully!

So there is a bug because there are no towers added, and they are not working but it says they are added.
@altostratous

**Comment by altostratous** [comment]
Added check for path in the validation logic in world::addTower
